{
 "title": "Leaf1 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BGP Neighbor Active Routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_afi_safi_active_routes{source=\"leaf1\"}",
     "legendFormat": "{{neighbor_peer_address}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"leaf1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_memory_utilization{source=\"leaf1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_memory_utilization{source=\"leaf1\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "platform_control_cpu_total_instant{source=\"leaf1\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Traffic Rate In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"leaf1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "platform_control_memory_free{source=\"leaf1\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Traffic Rate Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=\"leaf1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "CRC Error Frames In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "interface_ethernet_statistics_in_crc_error_frames{source=\"leaf1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Interface In Error Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "interface_statistics_in_error_packets{source=\"leaf1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Interface Out Error Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "interface_statistics_out_error_packets{source=\"leaf1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  }
 ]
}